name: network_image_cache
description: "Network image with cache technology."
version: 1.1.3
homepage: ''

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  hive_flutter: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0